#ifndef _DISPLAY_DEFINITIONS_H
#define _DISPLAY_DEFINITIONS_H

enum {
  DISPLAY_HOME = 0,
  DISPLAY_LIGHT_MENU,
  DISPLAY_LIGHT_ON_CONF,
  DISPLAY_LIGHT_OFF_CONF,
  DISPLAY_SET_POINT_MENU,
  DISPLAY_SET_POINT_TEMPERATURE_CONF,
  DISPLAY_SET_POINT_HUMIDITY_CONF,
  DISPLAY_MOTOR_MENU,
  DISPLAY_MOTOR_SPEED_CONF,
  DISPLAY_OPERATION_MODE_CONF,
};

#endif //_DISPLAY_DEFINITIONS_H